#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AUTH_ENV_FILE="/etc/software-cup-ops/software-cup-ops.env"

generate_token() {
  python - <<'PY'
import secrets

print(secrets.token_urlsafe(32))
PY
}

create_auth_env_file() {
  if [[ -f "${AUTH_ENV_FILE}" ]]; then
    echo "Auth environment file already exists: ${AUTH_ENV_FILE}"
    return
  fi

  install -d -m 750 /etc/software-cup-ops
  umask 077
  {
    echo "# Generated by deploy/install.sh. Paste one token into the frontend auth field."
    echo "AGENT_DEFAULT_ROLE=viewer"
    echo "AGENT_VIEWER_TOKEN=$(generate_token)"
    echo "AGENT_OPERATOR_TOKEN=$(generate_token)"
    echo "AGENT_ADMIN_TOKEN=$(generate_token)"
  } > "${AUTH_ENV_FILE}"
  chmod 600 "${AUTH_ENV_FILE}"
  echo "Created auth environment file: ${AUTH_ENV_FILE}"
}

if [[ "${EUID:-$(id -u)}" -eq 0 ]]; then
  bash "${SCRIPT_DIR}/setup-agent-user.sh"
  create_auth_env_file
fi

python -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt

echo "Install finished. Start with: uvicorn backend.main:app --host 127.0.0.1 --port 8000"
